version: '3.8'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8080:8080"
    networks:
      - my-network
    hostname: userservice
    
  challenge-service:
    build:
      context: ./challenge-service
    ports:
      - "8081:8081"
    networks:
      - my-network
    hostname: challengeservice

  submission-service:
    build:
      context: ./submission-service
    ports:
      - "8082:8082"
    networks:
      - my-network
    hostname: submissionservice

networks:
  my-network:
    driver: bridge
