version: '3.8'
services:
  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500" 
    networks:
      - my-network
    hostname: consul

  user-service:
    build:
      context: ./user-service
    depends_on:
      - consul
    networks:
      - my-network
    hostname: userservice
    
  challenge-service:
    build:
      context: ./challenge-service
    depends_on:
      - consul
    networks:
      - my-network
    hostname: challengeservice

  submission-service:
    build:
      context: ./submission-service
    depends_on:
      - consul
    networks:
      - my-network
    hostname: submissionservice

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8083:8083"
    networks:
      my-network:
        aliases:
          - gateway
    hostname: apigateway
    depends_on:
      - consul
      - user-service
      - challenge-service
      - submission-service

networks:
  my-network:
    driver: bridge
